#!/bin/bash

FILE="build.tc"
OUTPUT="app"

read_config() {
  if [ ! -f "$FILE" ]; then
    echo "build.tc not found"
    exit 1
  fi

  SRC=$(cat $FILE)
}

expand_sources() {
  EXPANDED=""

  for item in $SRC; do
    if [ -d "$item" ]; then
      EXPANDED="$EXPANDED $(find "$item" -type f \( -name "*.c" -o -name "*.cpp" -o -name "*.py" -o -name "*.java" \))"
    else
      echo "Error: '$item' is not a directory"
      exit 1
    fi
  done

  SRC=$EXPANDED
}

detect_lang() {
  FIRST=$(echo $SRC | awk '{print $1}')
  EXT="${FIRST##*.}"

  case "$EXT" in
    c) LANG="c" ;;
    cpp) LANG="cpp" ;;
    py) LANG="python" ;;
    java) LANG="java" ;;
    *)
      echo "Unsupported language: $EXT"
      exit 1
      ;;
  esac
}

build() {
  case "$LANG" in
    c)
      command -v gcc >/dev/null || { echo "gcc not installed"; exit 1; }
      gcc $SRC -o $OUTPUT
      ;;
    cpp)
      command -v g++ >/dev/null || { echo "g++ not installed"; exit 1; }
      g++ $SRC -o $OUTPUT
      ;;
    python)
      command -v python3 >/dev/null || { echo "python3 not installed"; exit 1; }
      python3 $SRC
      return
      ;;
    java)
      command -v javac >/dev/null || { echo "javac not installed"; exit 1; }
      javac $SRC
      ;;
  esac
}

run() {
  case "$LANG" in
    c|cpp)
      ./$OUTPUT
      ;;
    java)
      FIRST=$(echo $SRC | awk '{print $1}')
      java ${FIRST%.java}
      ;;
  esac
}

clean() {
  rm -f $OUTPUT *.class
  echo "Cleaned"
}

init() {
  if [ -f "$FILE" ]; then
    echo "build.tc already exists"
    exit 0
  fi

  echo "src" > $FILE
  echo "Created build.tc with default folder 'src'"
}

case "$1" in
  run)
    read_config
    expand_sources
    detect_lang
    build
    run
    ;;
  build)
    read_config
    expand_sources
    detect_lang
    build
    ;;
  clean)
    clean
    ;;
  init)
    init
    ;;
  *)
    echo "Usage: toolchain [run|build|clean|init]"
    ;;
esac