#!/bin/bash

OUTPUT="app"

SUPPORTED_EXTS=("c" "cpp" "py" "java")

detect_files() {
  FILES=$(find . -type f)

  C_FILES=""
  CPP_FILES=""
  PY_FILES=""
  JAVA_FILES=""

  for f in $FILES; do
    ext="${f##*.}"

    case "$ext" in
      c) C_FILES="$C_FILES $f" ;;
      cpp) CPP_FILES="$CPP_FILES $f" ;;
      py) PY_FILES="$PY_FILES $f" ;;
      java) JAVA_FILES="$JAVA_FILES $f" ;;
    esac
  done
}

detect_lang() {
  if [ -n "$CPP_FILES" ]; then
    LANG="cpp"
  elif [ -n "$C_FILES" ]; then
    LANG="c"
  elif [ -n "$PY_FILES" ]; then
    LANG="python"
  elif [ -n "$JAVA_FILES" ]; then
    LANG="java"
  else
    echo "No supported source files found"
    exit 1
  fi
}

build() {
  case "$LANG" in
    c)
      gcc $C_FILES -o $OUTPUT
      ;;
    cpp)
      g++ $CPP_FILES -o $OUTPUT
      ;;
    python)
      python3 $PY_FILES
      return
      ;;
    java)
      javac $JAVA_FILES
      ;;
  esac
}

run() {
  case "$LANG" in
    c|cpp)
      ./$OUTPUT
      ;;
    java)
      MAIN_CLASS=$(basename "$JAVA_FILES" .java)
      java $MAIN_CLASS
      ;;
  esac
}

clean() {
  rm -f $OUTPUT *.class
  echo "Cleaned"
}

case "$1" in
  run)
    detect_files
    detect_lang
    build
    run
    ;;
  build)
    detect_files
    detect_lang
    build
    ;;
  clean)
    clean
    ;;
  *)
    echo "Usage: toolchain [run|build|clean]"
    ;;
esac